import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Todo } from '../entity/todo.entity';

@Injectable()
export class TodoService {
  constructor(
    @InjectRepository(Todo)
    private readonly repo: Repository<Todo>,
  ) {}

  async getAll(): Promise<Todo[]> {
    return this.repo.find();
  }

  async getOwnAll(): Promise<Todo[]> {
    return this.repo.find({ where: { isDeleted: 0 } });
  }

  async getTodoById(todoId: number): Promise<Todo | null> {
    return this.repo.findOne({ where: { todoId } });
  }

  async addTodo(todo: Partial<Todo>): Promise<boolean> {
    const entity = this.repo.create({ ...todo });
    await this.repo.save(entity); // todoId will be generated by DB
    return true;
  }

  async updateTodo(todo: Partial<Todo>): Promise<boolean> {
    if (!todo.todoId) return false;
    await this.repo.update({ todoId: todo.todoId }, todo as any);
    return true;
  }

  async deleteTodo(todoId: number): Promise<boolean> {
    await this.repo.delete({ todoId });
    return true;
  }

  async deleteTodoMark(todoId: number): Promise<boolean> {
    const res = await this.repo.update({ todoId }, { isDeleted: 1 } as any);
    return (res.affected || 0) > 0;
  }
}
